name: 20×5h — Private Node runner

on:
  workflow_dispatch: {}  # no visible inputs

permissions:
  contents: read

jobs:
  run20:
    name: job ${{ matrix.idx }} — Node (≤5h)
    runs-on: ubuntu-latest
    timeout-minutes: 310    # hard cap; we'll soft-cap to 300m with `timeout`
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        idx: [0,1,2,3,4]

    steps:
      - name: Checkout PRIVATE repo
        uses: actions/checkout@v5
        with:
          repository: ${{ secrets.PRIVATE_REPO }}        # e.g. org/repo
          ref:        ${{ secrets.PRIVATE_REPO_REF }}    # e.g. main or a SHA
          token:      ${{ secrets.PRIVATE_REPO_TOKEN }}  # fine-grained PAT (Contents: Read)
          path:       private

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: private/package-lock.json

      - name: Install deps
        working-directory: private
        shell: bash
        run: |
          set -euo pipefail
          if [ -f package-lock.json ]; then
            npm ci --no-audit --progress=false
          else
            npm i  --no-audit --progress=false
          fi

      - name: Run for up to 5h
        working-directory: private
        shell: bash
        env:
          JOB_INDEX: ${{ matrix.idx }}
          RUN_MINUTES_SECRET: ${{ secrets.RUN_MINUTES }}   # optional override
        run: |
          set -euo pipefail
          RUN_MINUTES="${RUN_MINUTES_SECRET:-300}"
          echo "▶ Starting job $JOB_INDEX at $(date -Is) for ${RUN_MINUTES} minutes"
          timeout "${RUN_MINUTES}m" npx tsx src/index.ts
          echo "✅ Finished at $(date -Is)"
